PE-33-ImplmentLoginPage
ProjectEureka/project-eureka-flutter pull request #10
Opened 2021-02-05 00:27 UTC by txt020

What I did:
Implemented login and password widgets for login screen and signup screen. The user can now create an account and login with the same account or an existing account. Their info will be stored in Firebase.
How to test:

- Pull code from branch
- First thing you should see is the login screen.
 ![image](https://user-images.githubusercontent.com/38572314/106972021-e4bc2e00-6704-11eb-8712-194b579136a8.png)
You can either login with an existing account or create a new one.
- Click signup to create an account then enter an email and password.
- Both screens will redirect you the a basic homes screen and in your terminal the user uid will be displayed.
![image](https://user-images.githubusercontent.com/38572314/106972235-4ed4d300-6705-11eb-8085-427ec282d5ae.png)
Basic Home Screen:
![image](https://user-images.githubusercontent.com/38572314/106972248-54cab400-6705-11eb-9550-25ca61fb6734.png)

2021-02-05 23:45 UTC, ayeejane requested changes
A few things: 

1. When signing up, let the user know if the passwords they entered doesn't match.
2. Entering unmatched passwords still lets the user create their account. 
3. After signing up, let the user know their account has been created. Right now, after clicking `Register` nothing happens so there's no way of knowing if the user can proceed to logging in.
4. It lets the user sign in without signing up first.

2021-02-06 00:30 UTC, ayeejane requested changes
Pleae separate your files into screens and services folder

2021-02-06 00:30 UTC, ayeejane commented on lib/login_page.dart
> +  }
Right now, this is just a page route. Find a way to connect it to firebase

2021-02-06 00:30 UTC, ayeejane commented on lib/login_page.dart
> +
This button doesn't work, find a way to redirect the user to another screen so they can reset their password

2021-02-06 00:30 UTC, ayeejane commented on lib/sign_in.dart
> +
This function doesn't do anything, consider deleting it

2021-02-06 00:30 UTC, ayeejane commented on lib/signup_page.dart
> +          ),
This validator is not working properly. It doesn't correctly check if the passwords don't match

2021-02-06 00:30 UTC, ayeejane commented on lib/test.dart
> +}
What does this file do?

2021-02-06 00:40 UTC, tonynguyen98 commented
I haven't tested this myself, but judging from @ayeejane 's review, it seems like the majority of your task isn't working as intended. Please test your work before making a pull request.

2021-02-08 07:29 UTC, davidsquines requested changes
I tested the results and can validate Jane's findings:

1. Mismatching passwords still allow a new user to register
2. When entering an email, if the email already exists within firebase, the user is not notified. Please implement a notification where the user's email already exists within the system 
3. Password check functionality is not working. The app only seems to check if the email is present in the firebase database. it does not verify the password linked with the user account.

2021-02-10 22:50 UTC, davidsquines requested changes
After the user successfully creates the account, the user is immediately taken into the onboarding screen on the app. In other cases of register/login on other apps, the user is usually taken back to the login screen to test their credentials. Please implement this way instead

2021-02-10 23:24 UTC, ayeejane approved these changes
Everything works as intended now

2021-02-10 23:32 UTC, davidsquines approved these changes
Everything works as intended

2021-02-11 20:00 UTC, tonynguyen98 requested changes
Please make an auth services file and move anything that has to do with firebase into there. You've also got a lot of repeating code, but since it'll be a new issue to implement the UI for this, the person who's building the UI will clean up the code.

2021-02-11 20:00 UTC, tonynguyen98 commented on lib/screens/forgot_password.dart
> +                      auth.sendPasswordResetEmail(email: _email);
lets move this to a services file for all of authentication, kinda like how you did `signInWithGoogle()`.

2021-02-11 20:00 UTC, tonynguyen98 commented on lib/screens/login_page.dart
> +String _userEmail;
Please move this out of the global and into `_LoginPageState`

2021-02-11 20:00 UTC, tonynguyen98 commented on lib/screens/home_page.dart
> +}
Remember, after merging with main, use the home page that @MaxLian11 had created.

2021-02-11 20:00 UTC, tonynguyen98 commented on lib/screens/login_page.dart
> +        );
Send this to a services file and call it here.

2021-02-11 20:00 UTC, tonynguyen98 commented on lib/screens/signup_page.dart
> +final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
move these into `_SignupPageState()`

2021-02-11 20:00 UTC, tonynguyen98 commented on lib/screens/signup_page.dart
> +                              email: _userEmail, password: _password);
services file

2021-02-16 01:45 UTC, tonynguyen98 commented
> Please make an auth services file and move anything that has to do with firebase into there. You've also got a lot of repeating code, but since it'll be a new issue to implement the UI for this, the person who's building the UI will clean up the code.

Ignore this message, I just merge this code without making a services file. I will do that myself as my next task. This task itself already have been in-progress for 2 months.

2021-02-16 07:57 UTC, tonynguyen98 approved these changes

2021-02-16 07:58 UTC, merged