PE-38 | Implemented General and Payment pages
ProjectEureka/project-eureka-flutter pull request #12
Opened 2021-02-11 02:32 UTC by MaxLian11

WHAT I DID:

- Implemented General settings page. It has 3 setting switches and an About button that shows some information about Eureka.
- Implemented Payment settings page. It has 2 options: Google pay and Apple pay. Pages redirect users to the blank pages in which specific settings will be implemented in the next task. Blank pages have confirmation buttons that represent successfully saved data in the application.

HOW TO TEST

- Make sure to `flutter pub get`
- Settings must initially be switched off, but once changed, it must store persistent data and show the last changes after leaving the page or after closing the application.
![Screenshot_3](https://user-images.githubusercontent.com/68677129/107596873-f2265c00-6bcd-11eb-997e-6b147870cc1b.jpg)
- About page must appear on top of the settings page without overflowing and being able to close.
- Google Pay and Apple pay have logos and those must be pulled from Assets without errors or delays.
![Screenshot_4](https://user-images.githubusercontent.com/68677129/107596936-18e49280-6bce-11eb-9443-1b464656acb4.jpg)
- Confirmation message must redirect user back to settings without being able to go back to Google Pay or Apple Pay after confirmation alert.

2021-02-15 22:13 UTC, ayeejane requested changes

2021-02-15 22:13 UTC, ayeejane commented on lib/screens/settings/settings_payment.dart
> +          Divider(height: 20.0),
you don't need this divider

2021-02-15 22:13 UTC, ayeejane commented on lib/screens/settings/settings_payment.dart
> +          Text('Payment Methods', style: TextStyle(color: Colors.blue, fontSize: 30.0, fontWeight: FontWeight.bold), textAlign: TextAlign.center,),
make font smaller and align to the left instead of center

2021-02-15 22:18 UTC, MaxLian11 commented on lib/screens/settings/settings_payment.dart
> +          Divider(height: 20.0),
I made it to move the page down a little bit. Do you think it is bad if I used divider for that?

2021-02-15 22:29 UTC, MaxLian11 commented on lib/screens/settings/settings_payment.dart
> +          Divider(height: 20.0),
Ok, I figured it out

2021-02-15 22:48 UTC, ayeejane requested changes
Everything works as intended! Just made a few comments on UI changes.

2021-02-15 22:48 UTC, ayeejane commented on lib/screens/settings/settings_payment.dart
> +    leading: Container(padding: EdgeInsets.all(10.0), child: Image(image: image, width: 100.0), decoration: BoxDecoration(border: Border.all())),
make icons smaller

2021-02-17 22:47 UTC, tonynguyen98 approved these changes
Great work with this!

2021-02-17 22:49 UTC, ayeejane approved these changes
Looks good! :)

2021-02-17 23:39 UTC, merged