PE-40|Implement The Rating Page
ProjectEureka/project-eureka-flutter pull request #15
Opened 2021-02-19 03:17 UTC by txt020

**What I did:**

- Designed a rating system where the user can rate their experience with another user.
- User can touch and drag along a star bar, rating between 0 and 5.
- When user is done they can click the **DONE!** button to submit their rating.
- By default, if the user clicks on the DONE! button without giving a rating, it will auto fill zero for the rating.
- The rating is displayed while the user is giving a rating and will display again in console when rating is submitted.
- When rating is submitted user is routed back to homepage.
- The design look and feel is similar to what we agreed on Figma.

**How to Test:**

1. Pull from branch
2. Run flutter pub get
3. Test to make sure that ratings bar can slide from left to right.
4. Make sure the number rating is indicating the proper rating as you slide on the screen.
5. Once you submit make sure the rating you gave is displayed on your console.
6. Verify that  you're sent back to the homepage after, you click the **Done!** button.

2021-02-19 23:41 UTC, ayeejane requested changes
Just a few UI changes but also don't forget to create your branch off of main whenever you get a new task

2021-02-19 23:41 UTC, ayeejane commented on lib/screens/rating_page.dart
> +                  child: _submitButton('Done!'),
have the button be the same as `EurekaRoundedButton` , a component that Tony N. made for PE

2021-02-20 18:30 UTC, dominikyz requested changes
Code looks good. I could slide rating bar left and right, also, click on left and right side of the same star to add 0.5 and 1 point to rating accordingly.  After clicking done i was not taken to home page. i was taken to yellowish screen 
![image](https://user-images.githubusercontent.com/64664704/108604973-e8d38700-7365-11eb-8950-23feef2570d3.png)

Just a suggestion, we don't want users to force to Rate each experience. If rating is set automatically to 0 , it will bring down overall rating of the user. 
So at the moment when user gets "0 star rating" we can't differentiate  whether it was bad experience or simply experience was not rated. 
Possible solution to this might be to set _rating to NULL.
This way if user doesn't want to rate , it would not affect the rating of the person who helped.

Please let me know if this makes sense. I'm not the best with explanation lol

2021-02-20 21:04 UTC, tonynguyen98 requested changes
Overall, really clean code great job there. Just some changes to fix redundancy. Can you also add a `SizedBox()` between the _profilePicture and the first _heading? Good work otherwise.

2021-02-20 21:04 UTC, tonynguyen98 commented on lib/main.dart
> +      home: RatingPage(), // change back to LoginPage when done testing
I understand that you routed to the RatingsPage in main for test but dont forget to fix this after merging with main, for now you can route it after NewQuestionConfirmation.

2021-02-20 21:04 UTC, tonynguyen98 commented on lib/screens/rating_page.dart
> +        builder: (context) => Scaffold(
why do you need  to return a `MaterialApp()` with a `Builder()`?  Just return `Scaffold()` directly.

2021-02-20 21:04 UTC, tonynguyen98 commented on lib/screens/rating_page.dart
> +                Center(
You can remove this center because the center on line 27 will apply to the rest of the child. It's a bit redundant to have it here.

2021-02-20 21:04 UTC, tonynguyen98 commented on lib/screens/rating_page.dart
> +    return Center(
Same thing with this Center, its redundant.

2021-02-20 21:04 UTC, tonynguyen98 commented on lib/screens/rating_page.dart
> +    return RatingBar.builder(
Can you add an argument of `glow: false,` ? Just a styling change, I think the glow when dragging is tacky.

2021-02-22 03:15 UTC, ayeejane approved these changes
Looks good to me. Good job!

2021-02-22 05:35 UTC, tonynguyen98 approved these changes

2021-02-23 04:15 UTC, dominikyz commented
![image](https://user-images.githubusercontent.com/64664704/108801457-a3bc7a00-754a-11eb-8da4-045cf63c5a18.png)
 Getting pixel overflow error

2021-02-25 06:55 UTC, txt020 commented
@dominikyz Just fixed the bug you found. Thanks please let me know if it works on your end.

2021-02-25 20:39 UTC, dominikyz approved these changes
Everything works nicely! Good job!

2021-02-25 20:43 UTC, merged