PE-91 | Implemented EureQa Logo and Edited Onboarding Screens
ProjectEureka/project-eureka-flutter pull request #47
Opened 2021-04-28 06:31 UTC by ayeejane

What I Did: 

- Added the EureQa logo. 
- Edited the onboarding screens. 
- Removed unused images. 

How to Test: 

- Reinstall the app from your emulator or physical phone. 
- Go through the onboarding screens. Read the text as well.

2021-04-28 22:03 UTC, MaxLian11 approved these changes
Looks really good

2021-04-28 22:03 UTC, MaxLian11 commented on lib/screens/onboarding_screen.dart
>          ),
This slide is not necessary at this point as paying system has not been integrated yet. Consider comment it out for now

2021-04-28 22:17 UTC, tonynguyen98 requested changes
Please remove the white background from the images, and can you possibly make our login screen also have the gradient as well?

2021-04-29 19:37 UTC, dominikyz approved these changes
Looks outstanding! Awesome job!

2021-04-29 19:42 UTC, tonynguyen98 approved these changes
Great work! I seems you've figured out a way to remove one of the screens.

2021-04-29 19:59 UTC, merged