PE-35 | Implemented New Question Pages
ProjectEureka/project-eureka-flutter pull request #8
Opened 2021-02-01 21:40 UTC by tonynguyen98

**What I did:**

- Created Screens to allow a user to create new questions posts.
- Create some components for things we might use often.

**How To Test :**

- Clone repo and run `flutter pub get`.
- Navigate from the side menu to get to the "Create a New Question Page".
- Select a category from the 4.
- Check that the selector on top will switch between "Text" "Photo" and "Video"
- Return to the "Text" tab and fill out a Question Title and Question Body.
-  Click Submit and watch you debug console, you should see the values you've entered: 
![image](https://user-images.githubusercontent.com/36316432/106521354-fa2a2180-6492-11eb-9de9-82b5f50dd451.png)
- You should then see a confirmation screen, make sure that you can see your title and body here again.

2021-02-02 00:28 UTC, frlzjosh commented on lib/components/eureka_segmented_control.dart
> +
consider updating your command to the following 
```
/*
 * comment
 * /
```

2021-02-02 00:31 UTC, frlzjosh commented on lib/components/eureka_segmented_control.dart
> +
Disregard this comment, I just cited this document... this is diff than what I'm used to in java and python https://dart.dev/guides/language/effective-dart/documentation

2021-02-03 09:04 UTC, ayeejane requested changes

2021-02-03 09:04 UTC, ayeejane commented on lib/components/eureka_rounded_button.dart
> +/// Eureka. Please use this Widget when implementing and big buttons so
implementing big buttons?

2021-02-03 09:04 UTC, ayeejane commented on lib/components/eureka_text_form_field.dart
> +/// Eureka. Please use this Widget when any text form fields.
when using any text form fields

2021-02-03 09:04 UTC, ayeejane commented on lib/screens/new_question_screens/new_question_form.dart
> +        ),
Check if the user inputs just a single letter - should be invalid

2021-02-05 01:22 UTC, tonynguyen98 commented on lib/components/eureka_rounded_button.dart
> +/// Eureka. Please use this Widget when implementing and big buttons so
I was thinking, whenever we needed a button at the bottom the screen that is similar in size and shape. You can find something like this in profile onboarding and create a new question.

2021-02-06 01:16 UTC, ayeejane approved these changes
Looks good to me!

2021-02-08 07:37 UTC, davidsquines approved these changes
Works as intended and codebase is clean

2021-02-10 04:09 UTC, dominikyz reviewed
Code looks awesome, easy to read. Just have one suggestion for question submit page.
Also if user starts to type question, then goes to photo/video upload, and goes back to typing,  typed text is deleted. Should we have temp storage for that? Just a suggestion tho :)  Works as described otherwise

2021-02-10 04:09 UTC, dominikyz commented on lib/screens/new_question_screens/new_question_confirmation.dart
> +  }
Right now, when question is submitted,  we have 1 gray container that shows both title of question and question itself. May i suggest little correction so it's easier to distinguish where title ends :
easy one - make title text bold and maybe one font-size bigger that the question's text
harder one - display question submission in two separate containers (smaller one on top for title, and larger one on the bottom for question itself)

2021-02-10 04:46 UTC, merged